### ISSUE TITLE
Tentative Schedule

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#1]
http://digiah.github.io/DHGetDown/program.html @oksveta will update

**Comment by oksveta** [comment]
@rcrath @damg70 @rdbeales 
What do you guys think of the tentative schedule above? Do you expect any of the activities to take more or less time than suggested?

**Comment by rdbeales** [comment]
I think we should give an hour for welcome and coffee.  Just start it at 8:30 and let everyone wander in and give them time to chat.  Most conferences I've been too have been generous with this welcome period and I've really appreciated it.

**Comment by damg70** [comment]
Yes. Eat meet greet is always a good thing. 

:david

I'm all thumbs over here

**Comment by oksveta** [comment]
Sounds good. Welcome & Coffee from 8:30 to 9:30 it is.

**Comment by rcrath** [comment]
late to the party but looks good to me.

**Comment by rcrath** [comment]
adjusted times to give more to orientation on the task.  also could probably combine the soundcloud and google maps seesions into one.

**Comment by rcrath** [comment]
@digiah/dhgetdown can you all weigh in on switching the start from 9:30 to 9 in order to make enough time for the three presentations and discussion?

**Comment by oksveta** [comment]
8:30 - 9 welcome
9-10:20 - keynote
10:20-10:30 break
10:30-12: 00 collaborative story mapping part 1
lunch same
1-2:50 part ii
2:50-3 : break
3-4: wrap up

**Comment by oksveta** [comment]
schedule finalized and updated.
