### ISSUE TITLE
Paths (or locations)

### ISSUE THREAD

**Issue by rcrath** [digiah/DHGetDown#10]
Problem: allow someone with a smart phone to walk around campus and record a path upon which a story takes place.  

Plan: get longitude and latitudes for each location and create the path from that.  @damg70 will figure out how to drop pins or path in leaflet app.  

~~I have installed [owntracks](http://owntracks.org/) and have been exploring [the booklet](http://owntracks.org/booklet/guide).  I'll try setting up a server for it (#14)  in the next few days on dahi.  It seems to be able to do all of the mapping and exporting we want, it has free [apps, both ios/android](have installed [owntracks]%28http://owntracks.org/booklet/guide/apps/%29), and is well developed and designed to make new apps with.  [Development can be done in Python](http://owntracks.org/booklet/tech/program/) (hi @rdbeales ), but that might be on the longer term, since we won't be able to get something in the app store on short notice.  If we have the server and the free apps, people can go out, record their paths by using the manual on/off and keeping the app in the foreground (this might be difficult while recording too, especially in IOS!).  Maybe a buddy system, where two people go out together and one turns on the path while the other records their  story so both can be foreground.~~

~~One possible solution is [Google location history](http://google.com/locationhistory), which  does a pretty creepily good job of tracking my paths.  It is platform independent, though it needs an always logged in google account on yr smartphone.  Most people will have gmail through school.  If gmail or google maps is on your phone, there you go.  This might also be a good education lesson in surveillance!  What we need then is a way to extract select paths as map overlays/kmz files.  There are no menus I could find on the location maps, but maybe there is an api?  At API, I am officially out of my depth.  help @damg70 @rdbeales @oksveta !~~

**Comment by rcrath** [comment]
Info on getting the google tracking info out of google is [here](https://shkspr.mobi/blog/2015/09/get-your-google-location-history-the-hard-way-again/).  it is not too hard to get a kml file, but the file covers the whole day.  It seems like there might be a way to set it to give the kml file for between two times, but not sure.  THere might be better solutions the google way on their [api picker page](https://developers.google.com/maps/documentation/api-picker)

Other possibilities are [Glympse](https://developer.glympse.com/sdk), or I think more promising, [owntracks](http://owntracks.org/).  I'll explore the apps over the next few days and see if they are better than the google way.

**Comment by rcrath** [comment]
updated top post to reflect switch from google, which has no api, to owntracks, which I think has the whole mapping component.

**Comment by rcrath** [comment]
updated top to reflect latest plan.

**Comment by rcrath** [comment]
I will provide some coordinates to @damg70 to go with my story (see #12) on the [soundcloud playlist](https://soundcloud.com/digital-arts-hum-u-of-hi/sets/dhgetdown).

**Comment by rcrath** [comment]
@damg70 [my story](https://soundcloud.com/digital-arts-hum-u-of-hi/sets/dhgetdown) begins at 21.299213, -157.820924, goes to 21.299134, -157.821240 and returns to 21.299213, -157.820924

**Comment by damg70** [comment]
Ok folks (@rcrath @rdbeales  @oksveta), here's a first look at our little mapping webapp.

[http://metrohawaii.com/mapping/](http://metrohawaii.com/mapping/)

Buttons below the map reveal three baked-in paths.

You can click around on the map to get LATLONG locations, but that was really just so i could rapidly hardcode the points that build the paths.

the end of each path has a marker -- you can click that to get the pop-up that leads you to the soundcloud file associated with the story.

**Comment by oksveta** [comment]
Great! Looking forward to seeing it in action on the 18th. Let me know if you need anything from me ahead of time.
