### ISSUE TITLE
Collate results

### ISSUE THREAD

**Issue by rcrath** [digiah/DHGetDown#13]
This will be the afternoon session.  Perfect world would be a cross-platform mobile app or web app that can take #10 and #11 and put them together with everyone elses.  worst case scenario is that we share stories for this period and leave the app tba.

**Comment by rcrath** [comment]
update:  Soundcloud is viable, so closed #12.  It looks like the workflow will be like this:  

go to location of your story, walk and record story, getting coordinates at suitable points, take pix, return to afternoon session w/ recorded story to share with DAHI user who will put it on the [DHGetDown playlist](https://soundcloud.com/digital-arts-hum-u-of-hi/sets/dhgetdown), We will be able to enter coordinates for the stories into leaflet app that @damg70 will develop.  ANyone else want to test out a story?

**Comment by damg70** [comment]
Important variable:

I need to see if leaflet supports the zoom level that google maps does. So there is a chance that our little app will leverage Google over leaflet. 

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
google api sucks/is nonexist

**Comment by rcrath** [comment]
Afternoon sessions:
1. input data
2. a @damg70 build playlist
3. b. Rich sketches the app
4. present finished web page and tell stories
5. closure: look how easy to generate with minimal resources.  What could do with more support?

**Comment by oksveta** [comment]
👍👍👍
