### ISSUE TITLE
set up mqtt server

### ISSUE THREAD

**Issue by rcrath** [digiah/DHGetDown#14]
http://owntracks.org/booklet/guide/mqtt/

**Comment by rcrath** [comment]
I have the MQTT  set up on localhost. Still needed to hook it up securely and make it accessible outside the firewall

**Comment by damg70** [comment]
Quest que c'est mqtt?

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
@damg70 , See [here](http://owntracks.org/booklet/guide/mqtt/).

It is an IOT language that accepts commands from the owntracks iOS/android client to publish and read location/path coordinates for users it recognizes as having access. The actual server, called a [broker](http://owntracks.org/booklet/guide/broker/), is a program called [mosquitto](http://mosquitto.org/), which is the thing I have running on DAHI localhost but not accessible to world yet. The hope is that it will provide the base for #10.

**Comment by damg70** [comment]
Ah, I see. And exactly what (grins) am I building with this before the end of the month?

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
@damg70, #10. As soon as they open the firewall well see if that works.

**Comment by rcrath** [comment]
mqtt server and ios / android owntracks works using a username password method.  want to have it use TLS but have not gotten tht working.  I tracked myself walking to the store on owntracks today.

**Comment by rcrath** [comment]
Location is not accurate enough to use.
