### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#15]

**Comment by damg70** [comment]
![dh-getdown](https://cloud.githubusercontent.com/assets/6117953/17510738/e1e26d36-5dbb-11e6-9a00-0cf732a07604.png)

here's a first shot at the logo... see @rcrath @oksveta @rdbeales

**Comment by rcrath** [comment]
Works for me.  2 posibles things. 1.The Pokemon ref might be clearer with bolder primary colors like they use I think.  Not sure this would improve things as I like the color scheme now. 2. DH is low contrast/heard to read. Darken or lighten something but keep the grey?

**Comment by damg70** [comment]
lol. it's supposed to be subtle.

**Comment by rcrath** [comment]
ok, keep the subtlety.  THe spotlight on DH -- if that goes broader will it  provide enough contrast to make it more legible?  Maybe get @oksveta and @rdbeales eyes on it too, as I have little confidence in my skillz.  This will work if we procrastinate our way out too :)

**Comment by rcrath** [comment]
@damg70 did we use this on the handout?

**Comment by rcrath** [comment]
[DHGetdownLogo.pdf](https://github.com/digiah/DHGetDown/files/424478/DHGetdownLogo.pdf)
[DHGetdownLogo.pptx](https://github.com/digiah/DHGetDown/files/424477/DHGetdownLogo.pptx)

Here is a space-taker logo ppt for between presentations.
