### ISSUE TITLE
plan wrap up/coda

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#21]
examples of other mapping projects, beyond uh. 
scheduled for 3-4 pm, will also need a few minutes to say goodbye to everyone.

**Comment by rcrath** [comment]
contacted Huston about his sports mapping project

**Comment by oksveta** [comment]
FemTechNet Feminist Mapping: http://femtechnet.newschool.edu/feminist-mapping/

**Comment by rcrath** [comment]
Hi @rdbeales 

I can present on my music and performing arts in colonial America and Huston ( @phustonladner  ) can present on his sports stadium mapping project.  Let me know if either / both are on the program for the coda.

**Comment by rcrath** [comment]
closing issue as per @rdbeales email.  He and @oksveta will present for coda.
