### ISSUE TITLE
Registration at capacity?

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#22]
@digiah/dhgetdown 

Hi all: We've got 39 registrations (not including us or the keynotes) in under 24 hours. Fantastic. I've shared the registration document with you all, in case you want to browse the list. 

I closed registration and set up a [basic waitlist form](http://digiah.github.io/DHGetDown/registration.html) to collect contact information for those who are interested in more information if space becomes available. As the event draws closer, we can send a couple of reminders to the registered participants about the event and encouraging them to cancel their registration if they cannot make it. (A few no-shows are inevitable, but I do hope that most of the people registered to follow through.) 

What do you think? Should we capitalize on interest and find a way to expand capacity? 

Keep in mind, we are stretching our catering budget as it is and there is probably a limit to how many people we can coordinate for the mapping workshop at once. The room could fit quite a few more people for a lecture style-presentation, but 40 is about the limit for ensuring everyone gets table space to work. 

Happy weekend!

**Comment by rcrath** [comment]
Wow! this is fantastic.  I would like to expand a bit if we can.  I would like to browse the list.\*  Where did you share it? Can't find.  I can approach LLL for another $100 for catering.  SHould I? We could consider moving to the fourth floor conference room or the room where you guys gave your job talks.  that would also make telepresence easier since they have it.  

\* @oksveta if you would like I could give you and @rdbeales  acess to our super top secret high security internal google docs folder and you can keep it there.  Right now I think David and I are the only ones with access.  LMK.

**Comment by oksveta** [comment]
@rcrath Please go ahead and ask LLL. Maybe the fact that we are already at capacity plus 11 on the waitlist (50 total) will be convincing? 

We're already booked the room where we gave our job talks. It would fit up to 60 (maybe more? @rdbeales what do you think?), but folks might be a little cramped in terms of work space. If we want to provide access to laptops for the workshop, we only have 40. (Most people will probably have their own.)

PS here is a direct link to the [registration form](https://docs.google.com/a/hawaii.edu/forms/d/1IGP8Z0TEWQTtwBm4mKtRNNqySoWz-XQHnrkto5tDxh0/edit?usp=sharing) and to the [waitlist](https://docs.google.com/forms/d/1GgjA5mOxKYNoeCSMZCr8YdtrvCvSt0FNN42-cJr8eqw/edit?usp=sharing).

**Comment by rcrath** [comment]
@digiah/dhgetdown I updated the [event page](http://digiah.github.io/DHGetDown/) to reflect being full and the new livestreaming setup.  LMK if anything needs to change plz.  On a related note, what would you think of opening up the keynote and the coda to public to handle the overflow and just limiting the hands on portion?

**Comment by oksveta** [comment]
@digiah/dhgetdown  Can we take down the livestreaming details until we get consent from the presenters? I sent a message out this afternoon. You've all been copied. I don't foresee any of them not consenting, but I do think we need to be respectful. 

Re: opening keynote to more... Frankly, I think it will make things more complicated than need be. Especially if we are livestreaming, I don't know how much it would add to the experience.

**Comment by rcrath** [comment]
sorry to be slow on this.  I updated the page by commenting out the livestream links and removing reference to coda.  if/once we get permissions, we can just uncomment.

**Comment by oksveta** [comment]
Perfect solution. Thanks!

---

Sveta Stoytcheva
Humanities Librarian
University of Hawaiʻi at Mānoa
stoytch@hawaii.edu | (808) 956-7029

**Comment by rcrath** [comment]
@oksveta, closing this, ok?
