### ISSUE TITLE
Question about online availability

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#23]
@digiah/dhgetdown 

Hi all, 

Just got the following question re: dhgetdown: . 

"Any chance some of this will be accessible online for those who live away from Hawaii?" 

(I am not answering it until Monday, as I've already broken my for-the-love-of-god-don't-check-email-on-Saturday rule.) 

What do you think? 

I am all for broader accessibility, but  don't think the hands-on portion would be possible to replicate or manage. If the keynote speakers consent, we could record or stream the keynote portion and/or the coda. (This is also something we could send to the on-island folks who are interested, but weren't able to register.) 

If we agree that it is feasible/desirable to record/stream and the keynote speakers are OK with it, I'd just ask that somebody else volunteers to be the point person for that. 

Cheers.

**Comment by rcrath** [comment]
maybe we can livestream/periscope/skype the key note and closing.  @halljt  has experience doing this in the library conference room on the fourth floor, which would be great for us.  @halljt  could you help us set this up? I agree, the hands on would be difficult without actual presence, but if we did good handouts, people could conceivably reminisce accurately about particular paths at UH.  I gave David my [test data](https://github.com/digiah/DHGetDown/issues/10#issuecomment-232851944) without physically going to the site.  Just used the google map trick and soundcloud.  might be fun.  maybe we could set up a slack channel for distance participation.  I can be point person for this.  THis would also help with inter-island, etc access.

**Comment by oksveta** [comment]
@rcrath Awesome. Thanks for volunteering to be point person! Even if we can just do the non-hands on portions, I think folks will understand.

 Do you want to come to the library for a walk-through of the room?

**Comment by rcrath** [comment]
This is sorted.  We will stream to [youtube](https://www.youtube.com/embed/vYyoKXJixVg) from my iPad and and have a [notes & comments](https://goo.gl/c512v5) collaborative Google.  We need to send out an email blast at tleast to the DAHI list and the waiting list on this, so people who cannot come to the event can check it if they want to.  CLosing this issue.
