### ISSUE TITLE
INSTRUCTION LETTER

### ISSUE THREAD

**Issue by damg70** [digiah/DHGetDown#24]
Find the draft of the welcome / instruction letter attached. This should go out tomorrow after review by @rcrath @rdbeales or @oksveta ...
[letter.docx](https://github.com/digiah/DHGetDown/files/421241/letter.docx)

**Comment by oksveta** [comment]
@damg70 I can look at this today; I am also hoping to send out a reminder email to the registered participants this afternoon. 

Do you want them to have this ahead of time or will it be distributed at the workshop? What, if anything, do you hope people have done in advance?

**Comment by oksveta** [comment]
@damg70 @rcrath @rdbeales Looks good to me. I would only suggest renaming the "What to do" heading to – 

What to do (During the workshop)

– or similar. If no objections, I will attach this to the "Reminder you are registered for..." email this afternoon. (Will send around 2pm)

**Comment by damg70** [comment]
We want them to have this in advance so they know what to expect and we can minimize the shouting and pecking at screens...

:david

I'm all thumbs over here

**Comment by oksveta** [comment]
Sent. I will make some photocopies to distribute during the event, too.
