### ISSUE TITLE
Invite Panelists

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#3]
- [x] @damg70: Invite Noelani (Accepted)
- [x] @damg70 Invite kuʿualoha (Accepted)
- [X] @rcrath: Invite Jeannette (Accepted)
- [x] @rdbeales: ~~Invite someone from Geography~~

**Comment by rcrath** [comment]
@digiah/dhgetdown Jeanette Hall accepted

**Comment by damg70** [comment]
noelani has accepted.

**Comment by oksveta** [comment]
per @rdbeales, probably no geography panel member due to failed search in the department and a retirement.

**Comment by damg70** [comment]
I can ask ku’ualoha ho'owanamanui

**Comment by rcrath** [comment]
Plz do!

**Comment by rcrath** [comment]
@damg70 : any update on inviting ku’ualoha?

**Comment by rcrath** [comment]
If @kuualoha  cannot come, we could ask @amawyer to present on [MIPI](http://dahi.manoa.hawaii.edu/mipi/index.php/Main).

**Comment by rcrath** [comment]
I'm thinking four people in 45 minutes is too much.  maybe let's go with who we have?  ~~ALso the schedule needs breaks.  will fix that.~~

**Comment by kuualoha** [comment]
aloha, I just receive notification of this today; looking for the original message so I can respond appropriately...

**Comment by rcrath** [comment]
@kuualoha ooops we were supposed to invite you first! My bad.  We are having a mini-conference ([here is the announcement](http://digiah.github.io/DHGetDown/)) on August 18 and would like it very much if you could do a short presentation on your project during the keynote panel, 9:30 to 10:30.

**Comment by kuualoha** [comment]
aloha Rich,

Sounds great, I look forward to talking about my project.

malama,

ku'ualoha

On Thu, Jun 23, 2016 at 11:13 AM, Rich Rath notifications@github.com
wrote:

> @kuualoha https://github.com/kuualoha ooops we were supposed to invite
> you first! My bad. We are having a mini-conference (here is the
> announcement http://digiah.github.io/DHGetDown/) on August 18 and would
> like it very much if you could do a short presentation on your project
> during the keynote panel, 9:30 to 10:30.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/digiah/DHGetDown/issues/3#issuecomment-228185691, or mute
> the thread
> https://github.com/notifications/unsubscribe/ALFVXD5o33AifTRYYgNzobQ1ZJxZyRB1ks5qOvcIgaJpZM4Iiz9D
> .

## 

ku'ualoha ho'omanawanui
Director, Undergraduate Programs, English Department
Associate Professor of Hawaiian Literature

University of Hawai'i at Manoa
1733 Donaghho Rd. KUY 429
Honolulu, HI 96822
phone: (808) 956-3048
email: kuualoha@hawaii.edu

Author of *Voices of Fire, Reweaving the Literary Lei of Pele and
Hi‘iaka, *University
of Minnesota Press, 2014

**Comment by richrath** [comment]
Great, Thank you kuʿualoha!

**Comment by rcrath** [comment]
@kuualoha has graciously accepted, so that leaves three speakers but only 45-50 minutes once intros are made and all.  Might we want to revisit the schedule?  We really need to leave plenty of time for discussion on these to generate interest I think.  I'll take that up in #1 and close this.
