### ISSUE TITLE
Catering Budget

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#4]
Estimate cost for approx. 30 participants for 
- [x] Morning coffee
  1 Starbucks coffee traveler = 12 8 oz cups of coffee
  2 travelers x 13.95 = $27.90
- [x] Lunch from Da Spot
  Estimate cost: Catering has no fixed cost, they set up a menu according to your budget and number of meal choices and participants. 
  
  1 meal option, plus rice and salad, $6/person  x 30 = $180
  Multiple meal options, $10/person x 30 = $300 

Total budget: $250-300. 

Alternative: Sodexo/UH Dining Services Shoestring Catering. View menu here: https://uhm.sodexomyway.com/images/2015_Manoa_Shoestring_Guide_Publisher1_tcm640-87033.pdf

We can cater a really basic lunch (sandwiches) for $100. Two gallons of hot beverages would cost $39.98. We'd get the same amount of food as from outside caterers for $150. For $200, we could also get some breakfast pastries or side salad or something. 
- [ ] Request funds

**Comment by oksveta** [comment]
@rcrath, added Sodexo budget details above.

**Comment by rcrath** [comment]
@digiah/dhgetdown Any update on library funding?  A&H has agreed to kick in $100 "if the library is willing to kick in too."  I have yet to approach LLL but can do that once I have an answer about library.  BTW, there were concerns about "the community" coming, but if it is pre-registration, that should keep it from becoming free lunch for the masses, which seemed to be a worry.

**Comment by oksveta** [comment]
@rcrath Have initiated the formal request. Was waiting to hear back from you re: A&H, then was out of town.  My impression from earlier discussion with the UL is that we are likely to be approved if A&H is also supporting. $200 total should be plenty for the Sodexo menu.

**Comment by rcrath** [comment]
Yes. AH will pitch in$100 if library does. Should I ask lll Dean too?

**Comment by oksveta** [comment]
@digiah/dhgetdown  UL has approved $100 in funds from the library. With $100 from AH that should be sufficient for lunch & basic coffee break. I don't think it is necessary to also ask LLL unless there is an additional expense we have in mind.

**Comment by rcrath** [comment]
I have no idea how to set up the billing for this other than to ask the ah secretary, Janet Pinho Goldman which I can do. Who is the person in charge for such things for library?

**Comment by rcrath** [comment]
@oksveta will discuss with Linda

**Comment by rcrath** [comment]
closing
