### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#5]
- [x] Create Registration Form
- [x] Open Registration – by July 18
- [x] Close Registration – August 14 or when filled

**Comment by oksveta** [comment]
@rcrath @damg70 @rdbeales Let me know if the dates above seem reasonable. We can also open registration sooner.

**Comment by rdbeales** [comment]
Sounds good to me.

**Comment by rcrath** [comment]
Maybe have registration go up to the last minute if not filled?

**Comment by oksveta** [comment]
@digiah/dhgetdown 

The DAHI announcement just got sent out and we already have 5 registrations. I'll monitor the registration forms and keep you posted.

**Comment by oksveta** [comment]
28 registrations already (!)... I'll keep an eye out over the weekend, and switch to a waitlist if/when we top 40?

**Comment by rcrath** [comment]
@oksveta, closing, ok?
