### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#6]
- [ ] @rdbeales : Event poster
- [ ] @oksveta : Save the Dates – 1st week of June
- [ ] Open Registration (?) 
- [ ] KTUH @rcrath or @damg70 
- [ ]  UH events cal @rcrath or @damg70 
- [ ]  DAHI Events Cal @rcrath or @damg70 
- [ ] text for email campaign
- [ ]  email to [DAHI list](https://docs.google.com/spreadsheets/d/1ao2EPeu8ndHaQAEa7Qmab9BTru7iO0zOFqyqtpgPvK4/edit?usp=sharing) @rcrath or @damg70 
- [ ] Email to departments and additional list.   
- - [ ]  put the list together @digiah/dhgetdown 
- - [x] [google sheet](https://docs.google.com/spreadsheets/d/1-tJry0IFJL7f0tf6WEK6jKhE6nZt0Hkz1OPHY-JF56Y/edit?usp=sharing)
- [ ] Final Reminder, if spots still available (1 week before)
- [ ] Reminder to registered participants: August 15, August 17.

**Comment by rcrath** [comment]
I volunteer for doing the stuff signed to me or David G over the summer.  If it gets back to @damg70 's pay period, maybe he can help.

**Comment by oksveta** [comment]
Tasks here now distributed across several issues. Closed.
