### ISSUE TITLE
How many participants? 

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#8]
For planning/deciding when to cap registration, how many participants do we expect? 

The room can comfortably accommodate around 40 people; this morning someone mentioned they anticipated about 20 to attend? Should we aim/plan for approximately 30 participants?

@rcrath @rdbeales @damg70

**Comment by rcrath** [comment]
@oksveta My guess is that thirty is safe.

**Comment by rdbeales** [comment]
Agreed

**Comment by oksveta** [comment]
Sounds good! I'll get catering, etc. quotes for 30.
