### ISSUE TITLE
Code of Conduct?

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#9]
@rcrath @damg70 @rdbeales 

My strong preference is for events that I organize and attend to have a code of conduct. Are you guys open to this idea?

If we agree, the code of conduct will appear on the website and participants will be asked to accept the COC when registering. 

So far, no event I have organized has (thankfully!) required us to enforce the COC, but I think this small step goes a long way towards enacting more inclusive spaces, and perhaps could broaden the diversity of our participants. The[ ADA Initiative has done lots of great advocacy work ](https://adainitiative.org/continue-our-work/conference-policies/)for implementing anti-harassment policies at technology events, and an increasing number of library conferences also feature them. The [Wikimedia foundation also has a policy](https://wikimediafoundation.org/wiki/Friendly_space_policy) for all of their events. 

I propose the following CoC and look forward to your feedback. 
# Code of Conduct
## Anti-Harassment Policy

This event is intended to be a welcoming, supportive, and comfortable space for all participants, and we will work to make it a harassment-free environment. We will not tolerate harassment in any form.

Harassment includes offensive verbal comments related to race, ethnicity, sex, gender identity or expression, sexual orientation, country of origin, age, disability, physical appearance, body size, religion, veteran status or other protected class status; discriminatory or offensive images in public spaces; intimidation; stalking; harassing or unwanted photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Participants violating the anti-harassment policy may be warned or asked to leave by the event organizers.
## Recording/Social Media Policy

We see this event as a place to share information and build community, not only with other participants, but also with those who may not be able to attend. The event is, by default, considered open and can be written about on social media and photographed. If you do not want your picture taken, your words to be recorded or for either photographs or words to be attributed to you, please let other participants know that. As a courtesy, please always ask prior to creating sound or video recordings of any portion of this event. Please be thoughtful and respectful with your photographs, recording, and sharing.
## Reporting Harassment or Violations

If at any point during the event you feel uncomfortable or harassed, or if you witness any violations of these policies, please do not hesitate to reach out to Sveta Stoytcheva (stoytch@hawaii.edu) or anyone who introduces themselves at the start of the day as an event organizer. 
## Acknowledgements

This policy is based on the [Critlib Unconference Code of Conduct](http://critlib2015.weebly.com/code-of-conduct.html), which is based on the [NYC Archives Unconference Code of Conduct,](https://nycarchivesunconference.wordpress.com/code-of-conduct/) [SAA Code of Conduct](http://www2.archivists.org/statements/saa-code-of-conduct#.V0YhkGY8qG4), and the [AdaCamp event policies](https://adacamp.org/adacamp-toolkit/policies/#ahp).

**Comment by damg70** [comment]
I'm fully down with The CoC. I think it would also be good for the community to see it in action even though most people think it can't happen to them. 

Side note - confirmed participation of dr Noelani arista on our panel. 

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
CoC is added.  closing issue.
